#!/usr/bin/env bash
# prints To infinity and beyond infintly
clean_up() {
	rm "/var/run/myscript.pid"
	echo "I hate the kill command"
	exit 1
}
pid_file="/var/run/myscript.pid"
current_pid=$$
echo $current_pid > "$pid_file"
trap "rm /var/run/myscript.pid | exit 1" SIGQUIT
trap 'clean_up' SIGTERM
trap "echo Y U no love me?!" SIGINT
while true; do
	echo "To infinity and beyond"
	sleep 2
done
