#!/usr/bin/env bash
#displays certain string with certain values

count=1

while [ "$count" -lt 21 ]; do

	case "$count" in
	4)
		echo "$count"
		echo "bad luck from China"
		;;
	9)
		echo "$count"
		echo "bad luck from Japan"
		;;
	17)
		echo "$count"
		echo "bad luck from Japan"
		;;
	*)
		echo "$count"
		;;
	esac
	((count++))
done
